#!/bin/bash

echo "=========================================="
echo "SUBIR CÓDIGO A GITHUB"
echo "=========================================="
echo ""
echo "Repositorio configurado:"
echo "https://github.com/ServiciosTransaccionalesAndroid/casilleroback"
echo ""
echo "PASOS:"
echo ""
echo "1. Crea un Personal Access Token en GitHub:"
echo "   - Ve a: https://github.com/settings/tokens"
echo "   - Click en 'Generate new token (classic)'"
echo "   - Nombre: Casillero Backend"
echo "   - Permisos: Marca 'repo' (todos los permisos de repositorio)"
echo "   - Click 'Generate token'"
echo "   - COPIA EL TOKEN (solo se muestra una vez)"
echo ""
echo "2. Ejecuta el siguiente comando:"
echo ""
echo "   git push -u origin main"
echo ""
echo "3. Cuando te pida credenciales:"
echo "   - Username: aplicaciones.serviciostrans@gmail.com"
echo "   - Password: [PEGA EL TOKEN QUE COPIASTE]"
echo ""
echo "=========================================="
echo ""
echo "Commit listo para subir:"
git log --oneline -1
echo ""
echo "Archivos incluidos: 90 archivos, 9810 líneas"
echo ""
