spring:
  application:
    name: locker-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/locker_db
    username: locker_user
    password: locker_pass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: quasar1035@gmail.com
    password: kcrg pabt ldzs mady
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8080
  servlet:
    context-path: /

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true
    use-root-path: true

logging:
  level:
    com.servientrega.locker: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 28800000
  retrieval-code:
    length: 8
    expiration-hours: 48
