spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/locker_db}
    username: ${DATABASE_USERNAME:locker_user}
    password: ${DATABASE_PASSWORD:locker_pass}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    validate-on-migrate: false

server:
  port: ${PORT:8080}

logging:
  level:
    com.servientrega.locker: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
