spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/locker_db}
    username: ${DATABASE_USERNAME:locker_user}
    password: ${DATABASE_PASSWORD:locker_pass}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    validate-on-migrate: false

server:
  port: ${PORT:8080}
  tomcat:
    threads:
      max: 50
      min-spare: 10

resend:
  api:
    key: ${RESEND_API_KEY:}
  from:
    email: ${RESEND_FROM_EMAIL:quasar1035@gmail.com}
    name: ${RESEND_FROM_NAME:Servientrega}

logging:
  level:
    com.servientrega.locker: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
